package com.stech.enums;


public enum Action {
    VIEW,
    SAVE,
    UPDATE,
    DELETE,
    SERVICE_SEEKER_VIEW,
    SERVICE_SEEKER_SAVE,
    SERVICE_SEEKER_UPDATE,
    SERVICE_SEEKER_DELETE,
    SERVICE_PROVIDER_VIEW,
    SERVICE_PROVIDER_SAVE,
    SERVICE_PROVIDER_UPDATE,
    SERVICE_PROVIDER_DELETE;
}
